---
title: Déploiement d'une app Shiny
---


[Repo Github](https://github.com/BiodiversiteQuebec/shiny_hooks_node/blob/main/README.md)

## Connexion to rweb

```bash
ssh USERNAME@rweb.vhost33
```
# Navigate until the shiny folder & connect as shiny user
```bash
cd home/shiny
sudo su shiny
```

## Add a shiny app to rweb

1. Create a new SSH key with 

```bash
ssh-keygen -t rsa -f ~/.ssh/id_rsa.REPONAME
```

2. Add the `id_rsa.REPONAME.pub` file as a deploy key to the Github repo with a write access

3. Edit the `~/.ssh/config` file to add

```bash
Host REPONAME.github.com
  HostName github.com
  User git
  IdentityFile /home/shiny/.ssh/id_rsa.REPONAME
```

4. Git clone the repository in the shiny server

```bash
cd /srv/shiny-server
git clone git@REPONAME.github.com:BiodiversiteQuebec/REPONAME.git
```
# Steps to add a web hook for a repository
```bash
cd /home/shiny
```

5. Edit the `hook.js` file of the shiny_hooks_node app (`./shiny_hooks_node/`) to add the repo.
```bash
nano nano ./shiny_hooks_node/hook.js
```
Edit with
```js
gith({
    repo: 'BiodiversiteQuebec/REPONAME'
}).on( 'all', function( payload ) {
    if( payload.branch === 'master' )
    {
            // Exec a shell script
            execFile('/home/shiny/REPONAME_webhook.sh', function(error, stdout, stderr) {
                    // Log success in some manner
                    console.log( 'Tableau REPONAME updated' );
            });
    }
});
```

6. Create the `REPONAME_webhook.sh` file (for example `tableau_rarefaction_webhook.sh`) & edit it with the following commands.

```bash
#!/bin/bash

sudo -u shiny -H sh -c "cd /srv/shiny-server/REPONAME && git pull" 
sudo service shiny-server restart
```

7. Quit the Shiny user mode with `ctrl + d`and restart shiny hook with

```bash
sudo pm2 restart shiny-hook
```

8. Add the webhook to the GitHub repo (settings -> Webhooks) using https://coleo.biodiversite-quebec.ca/shinyhook/ and keeping the default settings


## View shiny apps logs

All logs are stored in the `var log` directory

```
sudo tail /var/log/shiny-server/
```

Associated [Github repository](https://github.com/BiodiversiteQuebec/shiny_hooks_node)
